# Generated by Django 5.2.8 on 2025-11-06 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PartyRegistry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('canonical_name', models.TextField()),
                ('short_name', models.TextField(blank=True, null=True)),
                ('country_code', models.CharField(max_length=3)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('merged', 'Merged'), ('split', 'Split'), ('renamed', 'Renamed'), ('dissolved', 'Dissolved')], default='active', max_length=16)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'party_registry',
            },
        ),
        migrations.CreateModel(
            name='ElectionEvent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('country_code', models.CharField(max_length=3)),
                ('election_type', models.CharField(choices=[('european_parliament', 'European Parliament'), ('national_parliament', 'National Parliament'), ('regional', 'Regional'), ('provincial', 'Provincial'), ('local', 'Local'), ('other', 'Other')], max_length=32)),
                ('election_date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'election_event',
                'indexes': [models.Index(fields=['election_date'], name='election_ev_electio_ceaff5_idx'), models.Index(fields=['country_code', 'election_type'], name='election_ev_country_fb9b3e_idx')],
            },
        ),
        migrations.CreateModel(
            name='GeoRegion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nuts_code', models.CharField(max_length=32)),
                ('nuts_level', models.PositiveSmallIntegerField()),
                ('name_official', models.TextField()),
                ('country_code', models.CharField(max_length=3)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'geo_region',
                'indexes': [models.Index(fields=['nuts_code', 'valid_from'], name='geo_region_nuts_co_241b41_idx'), models.Index(fields=['country_code', 'nuts_level', 'is_current'], name='geo_region_country_b0aaf6_idx')],
            },
        ),
        migrations.CreateModel(
            name='ElectionEventRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_reporting_unit', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporting_regions', to='core.electionevent')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='election_reporting', to='core.georegion')),
            ],
            options={
                'db_table': 'election_event_region',
                'unique_together': {('election', 'region')},
            },
        ),
        migrations.CreateModel(
            name='GeoRegionHierarchy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('child_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_links', to='core.georegion')),
                ('parent_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children_links', to='core.georegion')),
            ],
            options={
                'db_table': 'geo_region_hierarchy',
                'unique_together': {('parent_region', 'child_region', 'valid_from')},
            },
        ),
        migrations.CreateModel(
            name='PartyPositioning',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dimension', models.CharField(max_length=64)),
                ('value', models.DecimalField(decimal_places=3, max_digits=6)),
                ('source_system', models.CharField(max_length=64)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('confidence', models.DecimalField(decimal_places=2, max_digits=3)),
                ('notes', models.TextField(blank=True, null=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positioning', to='core.partyregistry')),
            ],
            options={
                'verbose_name_plural': 'Party Positioning',
                'db_table': 'party_positioning',
                'indexes': [models.Index(fields=['party', 'dimension', 'valid_from'], name='party_posit_party_i_55781b_idx')],
            },
        ),
        migrations.CreateModel(
            name='PartyAlias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('alias_name', models.TextField()),
                ('alias_type', models.CharField(choices=[('short_name', 'Short Name'), ('translation', 'Translation'), ('historical_name', 'Historical Name'), ('typo', 'Typo / Misspelling'), ('coalition_label', 'Coalition Label'), ('other', 'Other')], default='other', max_length=32)),
                ('source_system', models.CharField(max_length=64)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('confidence', models.DecimalField(decimal_places=2, max_digits=3)),
                ('added_by', models.CharField(blank=True, max_length=128, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='core.partyregistry')),
            ],
            options={
                'db_table': 'party_alias',
                'indexes': [models.Index(fields=['alias_name', 'source_system', 'valid_from'], name='party_alias_alias_n_6590c9_idx')],
            },
        ),
        migrations.CreateModel(
            name='DataQualityIssues',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('severity', models.CharField(choices=[('error', 'Error'), ('warning', 'Warning'), ('info', 'Info')], max_length=16)),
                ('issue_type', models.CharField(max_length=64)),
                ('source_system', models.CharField(blank=True, max_length=64, null=True)),
                ('details', models.TextField()),
                ('election', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_issues', to='core.electionevent')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_issues', to='core.georegion')),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_issues', to='core.partyregistry')),
            ],
            options={
                'db_table': 'data_quality_issues',
                'indexes': [models.Index(fields=['severity', 'issue_type'], name='data_qualit_severit_0ad0e0_idx'), models.Index(fields=['party'], name='data_qualit_party_i_c50f98_idx'), models.Index(fields=['election'], name='data_qualit_electio_b68a68_idx'), models.Index(fields=['region'], name='data_qualit_region__e2b137_idx')],
            },
        ),
        migrations.CreateModel(
            name='PartyResults',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('votes_pct', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('seats', models.IntegerField(blank=True, null=True)),
                ('turnout_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('source_system', models.CharField(max_length=64)),
                ('observed_at', models.DateTimeField()),
                ('quality_flag', models.CharField(choices=[('ok', 'OK'), ('suspect', 'Suspect'), ('manual_override', 'Manual Override')], default='ok', max_length=16)),
                ('notes', models.TextField(blank=True, null=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='core.electionevent')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='core.partyregistry')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='core.georegion')),
            ],
            options={
                'db_table': 'party_results',
                'indexes': [models.Index(fields=['election', 'region', 'party'], name='party_resul_electio_2092a0_idx'), models.Index(fields=['source_system', 'observed_at'], name='party_resul_source__4c56df_idx')],
            },
        ),
        migrations.CreateModel(
            name='PartySourceMap',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('source_system', models.CharField(max_length=64)),
                ('source_party_id', models.CharField(max_length=128)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('confidence', models.DecimalField(decimal_places=2, max_digits=3)),
                ('notes', models.TextField(blank=True, null=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_maps', to='core.partyregistry')),
            ],
            options={
                'db_table': 'party_source_map',
                'constraints': [models.UniqueConstraint(fields=('source_system', 'source_party_id', 'valid_from'), name='uniq_party_source_period')],
            },
        ),
    ]
