# Generated by Django 5.2.8 on 2025-11-06 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='georegion',
            name='name_official',
            field=models.TextField(blank=True, null=True),
        ),
    ]
