# Generated by Django 5.2.8 on 2025-11-06 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_georegion_name_official'),
    ]

    operations = [
        migrations.AlterField(
            model_name='georegion',
            name='country_code',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
