# Generated by Django 5.2.8 on 2025-11-06 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_georegion_country_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='georegion',
            name='nuts_code',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
