# Generated by Django 5.2.8 on 2025-11-15 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_georegion_nuts_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='DimensionDescriptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_system', models.CharField(blank=True, max_length=64, null=True)),
                ('macro', models.CharField(blank=True, max_length=64, null=True)),
                ('macro_label', models.CharField(blank=True, max_length=64, null=True)),
                ('variable', models.CharField(blank=True, max_length=64, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('label', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PartyPositioningLabel',
            fields=[
                ('dimension', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('label', models.TextField()),
            ],
        ),
    ]
