# Generated by Django 5.2.8 on 2025-11-16 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_dimensiondescriptor_partypositioninglabel'),
    ]

    operations = [
        migrations.AddField(
            model_name='electionevent',
            name='election_year',
            field=models.IntegerField(default=1900),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='electionevent',
            name='election_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
