# Generated by Django 5.2.8 on 2025-11-16 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_electionevent_election_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('parties', models.ManyToManyField(to='core.partyregistry')),
            ],
        ),
        migrations.DeleteModel(
            name='PartyPositioningLabel',
        ),
        migrations.AlterField(
            model_name='electionevent',
            name='election_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
