# Generated by Django 5.2.8 on 2025-11-16 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_party_delete_partypositioninglabel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electioneventregion',
            name='region',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='Party',
        ),
    ]
