# Generated by Django 5.2.8 on 2025-11-16 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_electioneventregion_region_delete_party'),
    ]

    operations = [
        migrations.AddField(
            model_name='partyalias',
            name='source_system_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
