# Generated by Django 5.2.8 on 2025-11-17 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_partyalias_source_system_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partypositioning',
            name='confidence',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='partypositioning',
            name='value',
            field=models.FloatField(),
        ),
    ]
