# Generated by Django 5.2.8 on 2025-11-19 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_partypositioning_confidence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partyalias',
            name='confidence',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='partyresults',
            name='turnout_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partyresults',
            name='votes_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partysourcemap',
            name='confidence',
            field=models.FloatField(),
        ),
    ]
