# Generated by Django 5.2.8 on 2025-12-11 15:16

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_partyalias_confidence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartyFamily',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='georegion',
            name='nuts_level',
            field=models.SmallIntegerField(),
        ),
        migrations.CreateModel(
            name='Coalition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('country_code', models.CharField(blank=True, help_text='Ridondante (di solito = coalition_party.country_code), ma utile per filtri.', max_length=3, null=True)),
                ('valid_from', models.DateField(default=datetime.date(1900, 1, 1))),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('source_system', models.CharField(blank=True, max_length=64, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('coalition_party', models.ForeignKey(help_text='PartyRegistry che rappresenta la coalizione (lista coalizionale).', on_delete=django.db.models.deletion.CASCADE, related_name='as_coalition', to='core.partyregistry')),
                ('election', models.ForeignKey(help_text='Elezione in cui questa coalizione è rilevante.', on_delete=django.db.models.deletion.CASCADE, related_name='coalitions', to='core.electionevent')),
            ],
            options={
                'db_table': 'coalition',
            },
        ),
        migrations.CreateModel(
            name='CoalitionMembership',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('weight_type', models.CharField(choices=[('equal', 'Equal Share'), ('votes', 'Votes-based'), ('seats', 'Seats-based'), ('custom', 'Custom Weight')], default='equal', help_text='Modo con cui ripartire i voti della coalizione sui membri.', max_length=16)),
                ('weight_share', models.DecimalField(blank=True, decimal_places=5, help_text='Quota 0–1 (se CUSTOM) oppure quota normalizzata calcolata da VOTES/SEATS.', max_digits=6, null=True)),
                ('raw_weight', models.DecimalField(blank=True, decimal_places=3, help_text='Valore grezzo (es. voti, seggi) usato per calcolare la share.', max_digits=12, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('coalition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.coalition')),
                ('member_party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coalition_memberships', to='core.partyregistry')),
            ],
            options={
                'db_table': 'coalition_membership',
            },
        ),
        migrations.AddIndex(
            model_name='coalition',
            index=models.Index(fields=['country_code', 'election'], name='coalition_country_092fb2_idx'),
        ),
        migrations.AddConstraint(
            model_name='coalition',
            constraint=models.UniqueConstraint(fields=('coalition_party', 'election'), name='uniq_coalition_party_election'),
        ),
        migrations.AlterUniqueTogether(
            name='coalitionmembership',
            unique_together={('coalition', 'member_party')},
        ),
    ]
