# Generated by Django 5.2.8 on 2025-12-30 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_dataexportjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportPreset',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('date_from', models.DateField()),
                ('country', models.CharField(blank=True, max_length=3, null=True)),
                ('election_type', models.CharField(blank=True, max_length=32, null=True)),
                ('nuts_level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('regions', models.JSONField(blank=True, help_text="Lista di NUTS code (es. ['ITC1','ITC2'])", null=True)),
                ('indicators', models.JSONField(blank=True, help_text="Lista dimensioni (es. ['rile','per108'])", null=True)),
                ('positioning_source', models.CharField(blank=True, max_length=64, null=True)),
                ('split_coalitions', models.BooleanField(default=False)),
                ('include_original_coalition', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'export_preset',
                'indexes': [models.Index(fields=['country', 'nuts_level'], name='export_pres_country_81079b_idx')],
            },
        ),
    ]
